### PR TITLE
update to 5.3.0 and py310

### PR DESCRIPTION
**Pull request by brey**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@thewtex I can't make it work for win. Maybe you know what needs to be done.

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@thewtex If you think it's ok, please merge in order to roll the ball for `itkwidgets` as well.

**Comment by sh-shahrokhi** [comment]
hello. please merge this one. Thanks

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Comment by brey** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
