### PR TITLE
Build ITK from Source

### PR DESCRIPTION
**Pull request by rlizzo**
This PR addresses https://github.com/conda-forge/itk-feedstock/issues/2. Instead of building packages from the pypi wheels, transition to building from source (with python bindings). This allows important optional modules (such as itkv3 compatability and itk review) to be included in build. 

I'm unsure if this will be built correctly, as I am unfamiliar with the conda-build toolchain package to set environment variables. Also, we may run into build time issues on MacOS, as the swig wrapping takes a long time (even when building locally), we may have to circle ci for macos to alleviate this problem

@msarahan, sorry for the tag, but I haven't received replies from the current maintainers in my last issue  https://github.com/conda-forge/itk-feedstock/issues/2. Wondering if you could give this recipe a quick review or if you could point me to the appropriate person on the conda-forge core team?

### CODE REVIEW

**Comment by isuruf** [comment]
Use other conda-forge pacakges instead of using the vendored copy. For eg: HDF5, jpeg, GDCM, swig

**Comment by isuruf** [comment]
Also, if there are third party libraries being built that are not in conda-forge, I suggest adding separate packages for them.

**Comment by rlizzo** [comment]
got it! updating now

**Comment by rlizzo** [comment]
Closing. This functionality is available in the libitk repo

**Pull request closed without merging**
