### PR TITLE
Bump ITK version to 4.13.0

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@conda-forge-admin @conda-forge-manager @ericdill 

The Windows builds did not get [pushed to Anaconda.org](https://anaconda.org/conda-forge/itk). Any ideas?

**Comment by isuruf** [comment]
@ocefpaf, @jakirkham, the webhook for appveyor was removed. Can you get the webhook url from appveyor and add it to this repo?

**Comment by jakirkham** [comment]
Added. Though you should also have permissions to do this.

**Comment by jakirkham** [comment]
Also triggered an AppVeyor build for `master`.

Edit: It's failing as this needs a re-render.

**Comment by thewtex** [comment]
Thanks @jakirkham @isuruf ! The win64 package is now on Anaconda.org. :v:

**Pull request merged**
