### PR TITLE
Update to patch release 4.11.1

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by bluescarni** [comment]
:+1: Looks good to me.

**Comment by blowekamp** [comment]
Based on the report from conda-forge/staged-recipes#2931, it is likely the windows builds are not working. Also in the test for this library we are only configuring and not installed.

Should we hold off updating until this issue is resolved?

**Comment by bluescarni** [comment]
It seems to be *almost* working on windows. It looks like most itk libs are correctly located and the issue seems to be confined to the hdf5 submodule.

Should we try to build the bundled hdf5 libs on windows only, until the issue is resolved upstream?

**Comment by bluescarni** [comment]
I restarted the appveyor build, one job had timed out due to network issues.

**Pull request merged**
