### PR TITLE
Bump version to 5.2.0

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by goanpeca** [comment]
Hello, is this ready for merge and release @mariusvniekerk, @thewtex?

Thanks!

**Comment by thewtex** [comment]
@mariusvniekerk @goanpeca thanks!

**Pull request merged**
